### ISSUE TITLE
Publishing to npm

### ISSUE THREAD

**Issue by timhudson** [lyft/coloralgorithm#10]
Are there any plans to publish this to [npm](https://npmjs.com)?

Also, thanks for open sourcing and sharing your approach. It's much appreciated!

**Comment by macintoshhelper** [comment]
Hi, I've published a fork of this repo to a scoped npm package: [`@elemental-design/coloralgorithm`](https://www.npmjs.com/package/@elemental-design/coloralgorithm) (Rollup compiled, so should work nicely with web bundlers)

Would be great if this could be published by Lyft too, should I open a PR for the Rollup bundling?
