### ISSUE TITLE
Is this the algorithm I seek?

### ISSUE THREAD

**Issue by jpstrikesback** [lyft/coloralgorithm#4]
Is this what was rumoured about at:

https://design.lyft.com/re-approaching-color-9e604ba22c88

and which powers:

https://www.colorbox.io/

Is it?

**Comment by rtpHarry** [comment]
According to this yes:

https://wptavern.com/lyft-open-sources-colorbox-algorithm-for-building-accessible-color-systems

(that's how I got here... the readme is pretty vague)

**Comment by soffes** [comment]
It is! Closing this as a duplicate of #7 since it's more specific about the ask :)
